import type { InvestmentOption, InvestmentRiskProfile } from "@/lib/domain";

type Seed = Pick<InvestmentOption,
  "id" | "name" | "classification" | "category" | "accountOrAsset" | "definition" |
  "returnMechanism" | "horizon" | "liquidity" | "incomeFrequency" | "passiveLevel" |
  "minimumAccessNotes" | "feesExpenseNotes" | "taxAccountNotes" | "diversification" |
  "incomeGeneration" | "sourceName" | "sourceUrl"> & { benchmark?: string; risk: "low" | "moderate" | "high" | "specialized" };

const risk = (kind: Seed["risk"]): InvestmentRiskProfile => {
  const level = kind === "low" ? "Low" : kind === "moderate" ? "Moderate" : "High";
  return {
    market: { level: kind === "low" ? "Low" : level, explanation: kind === "low" ? "Market-price movement is usually limited." : "Market value can move, sometimes sharply." },
    principal: { level, explanation: kind === "low" ? "Principal protection depends on product terms and applicable insurance or U.S. government backing." : "The amount invested can decline." },
    credit: { level: kind === "high" || kind === "specialized" ? "Varies" : level, explanation: "Repayment risk depends on the issuer and structure." },
    interestRate: { level: kind === "low" ? "Low" : "Moderate", explanation: "Rate changes can affect price or the attractiveness of the return." },
    inflation: { level: kind === "low" ? "Moderate" : "Varies", explanation: "Returns may or may not keep pace with purchasing-power changes." },
    liquidity: { level: kind === "specialized" ? "High" : "Low", explanation: kind === "specialized" ? "Access may be limited, delayed, or costly." : "Liquidity depends on trading, maturity, and withdrawal terms." },
    concentration: { level: kind === "high" || kind === "specialized" ? "High" : "Moderate", explanation: "Diversification depends on what the product actually holds." },
    regulatory: { level: kind === "specialized" ? "High" : "Low", explanation: "Rules, tax treatment, and investor protections vary by product and account." },
    complexity: { level: kind === "specialized" ? "High" : kind === "high" ? "Moderate" : "Low", explanation: "Understand the structure, costs, and access rules before using it." },
  };
};

const src = {
  investor: { sourceName: "SEC Investor.gov", sourceUrl: "https://www.investor.gov/introduction-investing/investing-basics/investment-products" },
  treasury: { sourceName: "U.S. Treasury / TreasuryDirect", sourceUrl: "https://www.treasurydirect.gov/marketable-securities/" },
  irs: { sourceName: "Internal Revenue Service", sourceUrl: "https://www.irs.gov/retirement-plans" },
  fdic: { sourceName: "FDIC", sourceUrl: "https://www.fdic.gov/resources/deposit-insurance/" },
};

const common = { symbol: "", minimumAccessNotes: "Varies by provider.", feesExpenseNotes: "Review provider fees and product expenses.", taxAccountNotes: "Tax treatment depends on the account and holding.", diversification: "Varies", incomeGeneration: "Varies" };

const seeds: Seed[] = [
  { id: "inv-sp500-benchmark", name: "S&P 500 Price Index", classification: "Benchmark", category: "Benchmarks", accountOrAsset: "Benchmark", benchmark: "", definition: "A price index measuring 500 leading U.S. companies. It is a benchmark, not a security you can buy directly.", returnMechanism: "Measurement only; investment products may track it.", horizon: "Long-term reference", liquidity: "Not purchasable", incomeFrequency: "None", passiveLevel: "Not applicable", risk: "moderate", ...common, ...src.investor },
  { id: "inv-taxable-brokerage", name: "Taxable Brokerage Account", classification: "Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "An account used to hold investments without a retirement tax wrapper.", returnMechanism: "The account itself has no return; holdings inside it create gains, income, or losses.", horizon: "Any", liquidity: "Depends on holdings", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-traditional-ira", name: "Traditional IRA", classification: "Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "An individual retirement account with tax rules governing contributions and withdrawals.", returnMechanism: "Performance comes from investments held inside the account.", horizon: "Very Long", liquidity: "Withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-roth-ira", name: "Roth IRA", classification: "Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A tax-advantaged individual retirement account funded with after-tax contributions, subject to IRS rules.", returnMechanism: "Performance comes from investments held inside the account.", horizon: "Very Long", liquidity: "Withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-401k", name: "401(k)", classification: "Employer Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "An employer-sponsored retirement plan that can hold a menu of investments.", returnMechanism: "Performance comes from investments held inside the plan.", horizon: "Very Long", liquidity: "Plan and withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-403b", name: "403(b)", classification: "Employer Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A retirement plan for eligible public-school and tax-exempt-organization employees.", returnMechanism: "Performance comes from investments held inside the plan.", horizon: "Very Long", liquidity: "Plan and withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-sep-ira", name: "SEP IRA", classification: "Self-Employed Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "An employer-funded IRA arrangement often used by self-employed people and small businesses.", returnMechanism: "Performance comes from investments held inside the account.", horizon: "Very Long", liquidity: "Withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-simple-ira", name: "SIMPLE IRA", classification: "Employer Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A retirement plan designed for eligible small employers and their employees.", returnMechanism: "Performance comes from investments held inside the account.", horizon: "Very Long", liquidity: "Withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-solo-401k", name: "Solo 401(k)", classification: "Self-Employed Retirement Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A 401(k) arrangement for an owner-only business, subject to eligibility and contribution rules.", returnMechanism: "Performance comes from investments held inside the plan.", horizon: "Very Long", liquidity: "Plan and withdrawal rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-hsa", name: "HSA Investment Account", classification: "Tax-Advantaged Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A health savings account that may offer an investment option after provider requirements are met.", returnMechanism: "Performance comes from investments held inside the account.", horizon: "Long", liquidity: "Qualified-expense and provider rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.irs },
  { id: "inv-529", name: "529 Plan", classification: "Education Account", category: "Investment Accounts", accountOrAsset: "Account", definition: "A tax-advantaged education savings plan with plan-specific investment choices.", returnMechanism: "Performance comes from investments held inside the plan.", horizon: "Long", liquidity: "Qualified-use rules apply", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-hysa", name: "High-Yield Savings Account", classification: "Deposit Account", category: "Cash & Capital Preservation", accountOrAsset: "Cash product", definition: "An interest-bearing bank or credit-union deposit account, often with a variable rate.", returnMechanism: "Interest", horizon: "Very Short", liquidity: "Same day / highly liquid", incomeFrequency: "Monthly interest is common", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.fdic },
  { id: "inv-cd", name: "Certificate of Deposit", classification: "Bank Deposit", category: "Cash & Capital Preservation", accountOrAsset: "Cash product", definition: "A time deposit that generally pays a stated rate for leaving money until maturity.", returnMechanism: "Interest", horizon: "Short to Intermediate", liquidity: "Maturity-based; early withdrawal penalty may apply", incomeFrequency: "Varies by term", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.fdic },
  { id: "inv-money-market", name: "Money Market Fund", classification: "Mutual Fund", category: "Cash & Capital Preservation", accountOrAsset: "Fund", definition: "A mutual fund investing in short-term, high-quality debt. It is not a bank deposit.", returnMechanism: "Interest income and distributions", horizon: "Very Short", liquidity: "Business-day liquidity", incomeFrequency: "Monthly distributions are common", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.investor },
  { id: "inv-tbill", name: "Treasury Bill", classification: "U.S. Government Security", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A short-term U.S. Treasury security sold at a discount or at par and paid at face value at maturity.", returnMechanism: "Discount accretion / interest", horizon: "Very Short to Short", liquidity: "Tradable; maturity-based if held directly", incomeFrequency: "At maturity", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.treasury },
  { id: "inv-tnote", name: "Treasury Note", classification: "U.S. Government Security", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A U.S. Treasury security with an intermediate maturity and semiannual interest.", returnMechanism: "Interest plus price change if sold before maturity", horizon: "Intermediate", liquidity: "Tradable; maturity-based", incomeFrequency: "Semiannual interest", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.treasury },
  { id: "inv-tbond", name: "Treasury Bond", classification: "U.S. Government Security", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A long-term U.S. Treasury security that pays semiannual interest.", returnMechanism: "Interest plus price change if sold before maturity", horizon: "Long", liquidity: "Tradable; maturity-based", incomeFrequency: "Semiannual interest", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.treasury },
  { id: "inv-tips", name: "TIPS", classification: "Inflation-Protected Treasury", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A Treasury security whose principal adjusts with CPI, affecting interest payments and maturity value.", returnMechanism: "Interest plus inflation adjustment", horizon: "Intermediate to Long", liquidity: "Tradable; maturity-based", incomeFrequency: "Semiannual interest", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.treasury },
  { id: "inv-ibond", name: "I Savings Bond", classification: "U.S. Savings Bond", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A nonmarketable U.S. savings bond with a composite rate combining a fixed rate and an inflation rate.", returnMechanism: "Composite interest rate", horizon: "Intermediate to Long", liquidity: "Cannot redeem for 12 months; early-redemption rules apply", incomeFrequency: "Accrued until redemption", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.treasury },
  { id: "inv-eebond", name: "EE Savings Bond", classification: "U.S. Savings Bond", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "A nonmarketable U.S. savings bond earning a fixed rate, with Treasury guarantee terms for eligible holding periods.", returnMechanism: "Fixed interest", horizon: "Long", liquidity: "Cannot redeem for 12 months; early-redemption rules apply", incomeFrequency: "Accrued until redemption", passiveLevel: "Low ongoing involvement", risk: "low", ...common, ...src.treasury },
  { id: "inv-corp-bond", name: "Corporate Bond", classification: "Debt Security", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "Debt issued by a company, with repayment depending on the issuer's ability to pay.", returnMechanism: "Interest and principal repayment; price changes if traded", horizon: "Short to Long", liquidity: "Varies", incomeFrequency: "Usually periodic interest", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-muni-bond", name: "Municipal Bond", classification: "Debt Security", category: "Bonds & Fixed Income", accountOrAsset: "Security", definition: "Debt issued by a state, locality, or related entity, with tax treatment and credit risk that vary.", returnMechanism: "Interest and principal repayment", horizon: "Intermediate to Long", liquidity: "Varies", incomeFrequency: "Usually periodic interest", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-bond-index", name: "Broad Bond Index Fund", classification: "Index Fund", category: "Bonds & Fixed Income", accountOrAsset: "Fund", definition: "A fund designed to track a diversified bond index. The fund is purchasable; the index is not.", returnMechanism: "Interest distributions and market-price change", horizon: "Intermediate to Long", liquidity: "Business-day liquidity", incomeFrequency: "Monthly distributions are common", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-treasury-fund", name: "Treasury Bond ETF / Fund", classification: "Fund", category: "Bonds & Fixed Income", accountOrAsset: "Fund", definition: "A pooled investment holding Treasury securities; its price can fluctuate even though the underlying securities are government-backed.", returnMechanism: "Interest distributions and market-price change", horizon: "Varies by duration", liquidity: "Business-day liquidity", incomeFrequency: "Monthly distributions are common", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-individual-stock", name: "Individual U.S. Stock", classification: "Equity Security", category: "Stocks & Equity", accountOrAsset: "Security", definition: "An ownership interest in one public company.", returnMechanism: "Capital appreciation and possible dividends", horizon: "Long", liquidity: "High for widely traded shares", incomeFrequency: "Dividends vary; appreciation has no schedule", passiveLevel: "Medium", risk: "high", ...common, ...src.investor },
  { id: "inv-us-index", name: "Broad U.S. Stock Index Fund", classification: "Index Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund designed to track a broad U.S. equity benchmark.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Distributions usually quarterly or annually", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-sp500-fund", name: "S&P 500 Index Fund", classification: "Index Fund", category: "Stocks & Equity", accountOrAsset: "Fund", benchmark: "S&P 500 Price Index", definition: "An ETF or mutual fund designed to track the S&P 500. Unlike the index, the fund is an investment product.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Distributions vary by fund", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-total-market", name: "Total U.S. Market Fund", classification: "Index Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund designed to track a broad cross-section of the U.S. stock market.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Distributions vary by fund", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-international", name: "International Stock Index Fund", classification: "Index Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund tracking stocks outside the United States; scope and country mix vary.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Distributions vary by fund", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-emerging", name: "Emerging Markets Fund", classification: "Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund focused on companies or markets in developing economies.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Variable distributions", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-small-cap", name: "Small-Cap Index Fund", classification: "Index Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund designed to track smaller public companies.", returnMechanism: "Capital appreciation plus dividends", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Distributions vary", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-dividend-fund", name: "Dividend Stock Fund", classification: "Equity Fund", category: "Stocks & Equity", accountOrAsset: "Fund", definition: "A fund emphasizing companies that pay dividends; dividends are not guaranteed.", returnMechanism: "Dividends plus capital appreciation", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Often quarterly", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-etf", name: "ETF", classification: "Fund Structure", category: "Funds", accountOrAsset: "Fund", definition: "An exchange-traded fund pools assets and trades during the day. ETF describes a structure, not a single investment strategy.", returnMechanism: "Depends on holdings", horizon: "Depends on holdings", liquidity: "Usually intraday; varies by fund", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-mutual-fund", name: "Mutual Fund", classification: "Fund Structure", category: "Funds", accountOrAsset: "Fund", definition: "A pooled investment priced at net asset value, generally once per business day.", returnMechanism: "Depends on holdings", horizon: "Depends on holdings", liquidity: "Business-day liquidity", incomeFrequency: "Depends on holdings", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-target-date", name: "Target-Date Retirement Fund", classification: "Diversified Fund", category: "Funds", accountOrAsset: "Fund", definition: "A diversified fund that changes its asset mix as a target year approaches. Strategies and costs vary.", returnMechanism: "Returns from underlying stock and bond holdings", horizon: "Very Long", liquidity: "Business-day liquidity inside account rules", incomeFrequency: "Variable distributions", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-balanced", name: "Balanced Fund", classification: "Diversified Fund", category: "Funds", accountOrAsset: "Fund", definition: "A fund combining stocks, bonds, and sometimes cash in a defined allocation.", returnMechanism: "Interest, dividends, and capital appreciation", horizon: "Intermediate to Long", liquidity: "Business-day liquidity", incomeFrequency: "Variable distributions", passiveLevel: "Low ongoing involvement", risk: "moderate", ...common, ...src.investor },
  { id: "inv-reit", name: "REIT", classification: "Real Estate Security", category: "Real Estate", accountOrAsset: "Security", definition: "A company that owns or finances income-producing real estate and generally distributes much of its taxable income.", returnMechanism: "Distributions and market-price change", horizon: "Long", liquidity: "High for publicly traded REITs; varies otherwise", incomeFrequency: "Often quarterly", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-reit-fund", name: "REIT Index Fund", classification: "Real Estate Fund", category: "Real Estate", accountOrAsset: "Fund", definition: "A pooled fund holding multiple REITs, providing broader real-estate-company exposure than one REIT.", returnMechanism: "Distributions and capital appreciation", horizon: "Long", liquidity: "Business-day liquidity", incomeFrequency: "Often quarterly", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-direct-real-estate", name: "Direct Real Estate", classification: "Real Asset", category: "Real Estate", accountOrAsset: "Asset", definition: "Direct ownership of property. This links conceptually to the existing rental-property workspace rather than replacing it.", returnMechanism: "Rent, appreciation, or both", horizon: "Long", liquidity: "Illiquid", incomeFrequency: "Rent may be monthly", passiveLevel: "High ongoing involvement", risk: "specialized", ...common, ...src.investor },
  { id: "inv-commodity", name: "Commodity Fund", classification: "Alternative Fund", category: "Alternative Assets", accountOrAsset: "Fund", definition: "A fund providing exposure to commodities through physical holdings, futures, producers, or a combination.", returnMechanism: "Market-price change; structure-dependent income", horizon: "Varies", liquidity: "Usually business-day liquidity", incomeFrequency: "Usually none or variable", passiveLevel: "Low ongoing involvement", risk: "specialized", ...common, ...src.investor },
  { id: "inv-gold", name: "Gold / Precious Metals", classification: "Alternative Asset", category: "Alternative Assets", accountOrAsset: "Asset", definition: "Exposure to precious metals through physical holdings or investment products; each structure has different costs and risks.", returnMechanism: "Market-price change", horizon: "Varies", liquidity: "Varies by form", incomeFrequency: "None", passiveLevel: "Low ongoing involvement", risk: "high", ...common, ...src.investor },
  { id: "inv-crypto", name: "Crypto Assets", classification: "Specialized Alternative", category: "Alternative Assets", accountOrAsset: "Asset", definition: "Digitally represented assets with substantial price, custody, technology, and regulatory risks.", returnMechanism: "Market-price change; no guaranteed cash flow", horizon: "Speculative / varies", liquidity: "Varies", incomeFrequency: "Usually none", passiveLevel: "Medium", risk: "specialized", ...common, ...src.investor },
  { id: "inv-private", name: "Private Equity / Private Investment", classification: "Specialized Alternative", category: "Alternative Assets", accountOrAsset: "Asset", definition: "An investment in a nonpublic company or private fund, often with eligibility restrictions and limited liquidity.", returnMechanism: "Business distributions or eventual sale", horizon: "Very Long", liquidity: "Illiquid", incomeFrequency: "Variable", passiveLevel: "Medium", risk: "specialized", ...common, ...src.investor },
  { id: "inv-collectibles", name: "Collectibles", classification: "Specialized Alternative", category: "Alternative Assets", accountOrAsset: "Asset", definition: "Physical items valued by collector demand; pricing, authenticity, storage, and resale can be difficult.", returnMechanism: "Resale price change", horizon: "Varies", liquidity: "Limited / illiquid", incomeFrequency: "None", passiveLevel: "Medium", risk: "specialized", ...common, ...src.investor },
];

export const INVESTMENT_CATALOG = seeds.map(seed => ({ ...seed, riskProfile: risk(seed.risk) }));
