/// <reference types="vite/client" />

// Migrations are generated by `npm run db:generate` into /drizzle and applied here on the
// first request, so a fresh local database (or a new deploy) needs no manual wrangler step.
const files = import.meta.glob("../drizzle/*.sql", { query: "?raw", import: "default", eager: true }) as Record<string, string>;

/**
 * D1 may start more than one Worker isolate at the same time. Keep schema-creation
 * statements repeatable so concurrent first requests cannot strand the database
 * between "object created" and "migration recorded".
 */
function repeatable(statement: string) {
  return statement
    .replace(/^CREATE TABLE\s+(?!IF NOT EXISTS\s+)/i, "CREATE TABLE IF NOT EXISTS ")
    .replace(/^CREATE UNIQUE INDEX\s+(?!IF NOT EXISTS\s+)/i, "CREATE UNIQUE INDEX IF NOT EXISTS ")
    .replace(/^CREATE INDEX\s+(?!IF NOT EXISTS\s+)/i, "CREATE INDEX IF NOT EXISTS ");
}

async function columnExists(d1: D1Database, table: string, column: string) {
  const safeTable = table.replace(/[^a-zA-Z0-9_]/g, "");
  const rows = await d1.prepare(`PRAGMA table_info(${safeTable})`).all<{ name: string }>();
  return rows.results.some(row => row.name === column);
}

async function applyStatement(d1: D1Database, statement: string) {
  const alter = statement.match(/^ALTER TABLE\s+[`"]?([\w]+)[`"]?\s+ADD\s+[`"]?([\w]+)[`"]?/i);
  if (alter && await columnExists(d1, alter[1], alter[2])) return;
  try {
    await d1.prepare(repeatable(statement)).run();
  } catch (error) {
    // A concurrent isolate may have added the same column after our check.
    if (alter && await columnExists(d1, alter[1], alter[2])) return;
    throw error;
  }
}

export async function runMigrations(d1: D1Database) {
  await d1.prepare("CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)").run();
  const done = await d1.prepare("SELECT name FROM _migrations").all<{ name: string }>();
  const applied = new Set(done.results.map(r => r.name));

  for (const [path, sql] of Object.entries(files).sort(([a], [b]) => a.localeCompare(b))) {
    const name = path.split("/").pop() as string;
    if (applied.has(name)) continue;
    const statements = sql.split("--> statement-breakpoint").map(s => s.trim()).filter(Boolean);
    for (const statement of statements) await applyStatement(d1, statement);
    await d1.prepare("INSERT OR IGNORE INTO _migrations (name, applied_at) VALUES (?, ?)").bind(name, new Date().toISOString()).run();
  }
}
